#!/bin/bash

# @license
# Copyright 2026 Google Inc.
# SPDX-License-Identifier: Apache-2.0

set -e

# 1. Verify git working directory is clean before we start
if [ -n "$(git status --porcelain)" ]; then
  echo "Error: Your git working directory is not clean." >&2
  echo "Please commit, stash, or discard your changes before running this script." >&2
  exit 1
fi

# 2. Check requirements
if ! command -v gh &> /dev/null; then
  echo "Error: 'gh' CLI is required but not installed." >&2
  echo "Please install it first (e.g. 'brew install gh')." >&2
  exit 1
fi

if ! gh auth status &> /dev/null; then
  echo "Error: You are not authenticated with 'gh' CLI." >&2
  echo "Please run 'gh auth login' first." >&2
  exit 1
fi

if ! command -v cddlconv &> /dev/null; then
  echo "Warning: 'cddlconv' is not installed or not in PATH." >&2
  echo "The build step might fail. You can install it using: cargo install cddlconv@0.1.7" >&2
else
  CDDLCONV_VERSION=$(cddlconv --version 2>&1 | awk '{print $2}')
  if [ "$CDDLCONV_VERSION" != "0.1.7" ]; then
    echo "Warning: 'cddlconv' version is $CDDLCONV_VERSION, but 0.1.7 is required." >&2
    echo "You can install the correct version using: cargo install cddlconv@0.1.7" >&2
  fi
fi

# 3. Run build/regeneration steps
echo "Running build and regeneration..."
npm test

# 4. Check if any changes were produced
CHANGES=$(git status --porcelain)
if [ -z "$CHANGES" ]; then
  echo "No changes detected. Webdriver BiDi types are up to date!"
  exit 0
fi

echo "Changes detected:"
echo "$CHANGES"

# 5. Check out a branch for regeneration
BRANCH_NAME="regenerate"
CURRENT_BRANCH=$(git branch --show-current)

echo "Creating and switching to branch '$BRANCH_NAME'..."
git checkout -B "$BRANCH_NAME"

# 6. Commit the changes
echo "Committing changes..."
# Stage all changes (including untracked/newly generated files)
git add -A

# Commit using the user's configured git user
git commit -m "fix: re-generate types based on spec updates"

# 7. Push the branch
echo "Pushing '$BRANCH_NAME' branch to remote..."
git push -f origin "$BRANCH_NAME"

# 8. Create or update the Pull Request
echo "Creating/updating Pull Request..."

PR_TITLE="fix: re-generate types based on spec updates"
PR_BODY="Automatically generated by tools/regenerate.sh"

# Check if a PR already exists for this head branch
EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number')

if [ -n "$EXISTING_PR" ]; then
  PR_URL=$(gh pr view "$EXISTING_PR" --json url --jq '.url')
  echo "Pull Request #$EXISTING_PR already exists for branch '$BRANCH_NAME'."
  echo "The branch has been force-pushed and the PR is now updated."
  echo "PR URL: $PR_URL"
else
  # Create a new PR
  PR_URL=$(gh pr create \
    --title "$PR_TITLE" \
    --body "$PR_BODY" \
    --head "$BRANCH_NAME" \
    --base main)
  echo "Created Pull Request: $PR_URL"
fi

# 9. Switch back to original branch
if [ -n "$CURRENT_BRANCH" ] && [ "$CURRENT_BRANCH" != "$BRANCH_NAME" ]; then
  echo "Switching back to your original branch: $CURRENT_BRANCH..."
  git checkout "$CURRENT_BRANCH"
fi

echo "Regeneration automation complete!"
